import React, {useState} from 'react';
import {useNavigate} from "react-router-dom";
import {FormField} from "../components/index.js";
import {getRandomPrompt} from "../utils/index.js";

const CreatePost = () => {
    const navigate = useNavigate()
    const [form, setForm] = useState({
        name: '',
        prompt: '',
        photo: '',
    });

    const [generatingImg, setGeneratingImg] = useState(true);
    const [loading, setLoading] = useState(false);


    const generateImg = async () => {
        if (form.prompt) {
            try {
                setGeneratingImg(true)
                const response = await fetch("http://localhost:8080/api/v1/dalle", {
                    method: 'POST',
                    headers: {
                        "Content-Type": 'application/json'
                    },
                    body: JSON.stringify({prompt: form.prompt})

                })

                const data = await response.json()

                setForm({...form, photo: `data:image/jpeg;base64, ${data.photo}`})
            } catch (e) {
                alert(e)
            } finally {
                setGeneratingImg(false)
            }
        } else {
            alert("Please enter a prompt")
        }
    }
    const handleSubmit = () => {

    }
    const hanleChange = (e) => {
        setForm({...form, [e.target.name]: e.target.value})
    }

    const handleSurpriseMe = () => {
        const randomPrompt = getRandomPrompt(form.prompt)
        setForm({...form, prompt: randomPrompt})
    }

    return (
        <section className='max-x-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[32px]'>
                    Create
                </h1>
                <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
                    Create through a collection of imaginative and visually stunning images generated by DALL-E AI
                </p>


            </div>

            <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
                <div className='flex flex-col gap-5'>
                    <FormField
                        labelName="Pormpt"
                        type='text'
                        name='prompt'
                        placeholder='a stained glass window depicting a hamburger and french fries'
                        value={form.prompt}
                        handleChange={hanleChange}
                        isSurpriseMe
                        handleSurpriseMe
                    />
                </div>
                <div className='mt-5 flex gap-5'>
                    <button type='button' onClick={generateImg}
                            className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
                    >
                        {generateImg ? 'Generating...' : 'Generate'}
                    </button>
                </div>
                <div className='mt-10'>
                    <p className='mt-2 text-[#666e75] text-[14px]'>Once you have created the image you want, you can
                        share it with community</p>
                    <button type='submit'
                            className='mt-3 text-white bg-[#6369ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 pt-2.5 text-center'
                    >
                        {loading ? "Sharing..." : "Share with the community"}
                    </button>
                </div>
            </form>
        </section>
    );
};

export default CreatePost;