import React, {useState} from 'react';
import {useNavigate} from "react-router-dom";
import {FormField} from "../components/index.js";

const CreatePost = () => {
    const navigate = useNavigate()
    const [form, setForm] = useState({
        name: '',
        prompt: '',
        photo: '',
    });

    const [generatingImg, setGeneratingImg] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleSubmit = () => {

    }
    const hanleChange = (e) => {

    }

    const handleSurpriseMe = () => {}

    return (
        <section className='max-x-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[32px]'>
                    Create
                </h1>
                <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
                    Create through a collection of imaginative and visually stunning images generated by DALL-E AI
                </p>


            </div>

            <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
                <div className='flex flex-col gap-5'>
                    <FormField
                        labelName="Pormpt"
                        type='text'
                        name='prompt'
                        placeholder='a stained glass window depicting a hamburger and french fries'
                        value={form.prompt}
                        handleChange={hanleChange}
                        isSurpriseMe
                        handleSurpriseMe
                    />
                </div>
            </form>
        </section>
    );
};

export default CreatePost;